### PR TITLE
Update generation from corrected manual bindings

### PR DESCRIPTION
**Pull request by Bahlph**
Manual bindings were changed:
- Added new members to `VkmaAllocatorCreateInfo` and `VkmaTotalStatistics`
- Changes that reflect `vmaCalculateStats` being renamed to `vmaCalculateStatistics`
- `vkmaEndDefragmentation` now returns void like its vma counterpart
- `vkmaVirtualFree` now returns void like its vma counterpart
- `vkmaBeginDefragmentationPass` no longer takes a const `VkmaDefragmentationPassMoveInfo`
- `vkmaEndDefragmentationPass` no longer takes a const `VkmaDefragmentationPassMoveInfo`
- `vkmaGetPoolStatistics` and `vkmaCalculatePoolStatistics` call their correct vma versions
- `vkmaEndDefragmentationPass` takes a `context`, not a `pContext`

### CODE REVIEW

**Comment by Cvelth** [comment]
Thanks for the PR, but could you also update the submodule commits as well? So that when a recursive clone is done, the correct versions of all the repositories are fetched? (it also involves making a PR for `vkma_xml_generator` since it depends on `vkma_bindings` as well)

**Comment by Cvelth** [comment]
Ah, wait, it's my bad. I changed the main repository after this PR was created, can you rebase please?

**Comment by Cvelth** [comment]
It looks like the final header is formatted with different clang-format configs.

Sorry I'm bothering you so much with this PR, but could you please double-check which config it's using?

**Comment by Bahlph** [comment]
Don't worry about it, it's no bother; I'm not sure why clang-format isn't playing nicely with me today.  Is that correct now?

**Comment by Cvelth** [comment]
No, I'm still getting a different result. And I have no idea why it could be.

WAIT! What version of clang-format are you on?

**Comment by Bahlph** [comment]
I'm not quite sure which one it is, but I was just having Visual Studio 2022 use whichever version of clang-format it ships with.  If you could point me towards another way to get the right formatting with the right version, I'm all for it.

**Comment by Cvelth** [comment]
It looks like I marked this config with clang-format-12, so if you could manually run (from the console/wsl/whatever) clang-format-12 in this directory, it would be really nice.

**Comment by Bahlph** [comment]
Fingers crossed that WSL saved the day; is it correct now?

**Comment by Cvelth** [comment]
I've just pushed some stuff related to the remaining known issues, could you rebase this PR (and also update `vkma_xml_generator` submodule) and try it out, please?

**Comment by Bahlph** [comment]
Works perfectly; thanks so much!

**Comment by Cvelth** [comment]
I think I have found what was causing weird clang-format behaviour, please take it for a spin (rebase and update then the submodules).

P. S. Please also squash the commits together.

**Comment by Cvelth** [comment]
Looks really good! Thanks for the effort.

Closes #1

**Pull request merged**
